#!/bin/bash

backup_drive=/media/spare

# incremental backup of svn repositories
pyrsync $HOME/repos/ $backup_drive/backups/repos

# incremental backup of all Pictures
pyrsync $HOME/Pictures/ $backup_drive/backups/Pictures

# single backup of cyclus repo
rm -Rf $backup_drive/backups/git/cyclus_rcore
git clone $HOME/git/rcore $backup_drive/backups/git/cyclus_rcore

date >> /home/robert/local-backup-log.txt

